<?php
$objectManager =  \Magento\Framework\App\ObjectManager::getInstance();        
$storeManager  = $objectManager->get('\Magento\Store\Model\StoreManagerInterface');

$storeCode = $storeManager->getStore()->getCode();
$logoNobuck = $this->getViewFileUrl('images/logo-nobuck.jpg');
$logoTintopro = $this->getViewFileUrl('images/logo-tintopro.jpg');

 ?>

<style>
.cambiador {
    position:fixed;
    left: 0px;
    width: 45px;
    height: 100%;
    transition: all 1s;
    z-index: 9999;
}
.cambiador.active {
    width: 250px;
    opacity: 1;
}
.cambiador .img {
    padding:0px;
}

.cambiador .pestana-contenido {
   width: 100%;
   visibility: hidden;
   opacity: 0;
}
.cambiador.active .pestana-contenido {
    width: 100%;
    visibility: visible;
    opacity: 1;
}

.pestana-contenido {
    height: 100%;
    width: 250px;
    background-color: <?php echo ($storeCode == 'n_es') ? '#cba472' : '#352e74'; ?>;
    border-radius: 0px 10px 10px 0px;
    border-right: 1px solid grey;
    overflow: hidden;
    margin-right: 10px;
    transition: all 1s;
}

.cambiador.active .cambiador-icon {
    color: white;
    right: -15px;
}
.pestana-contenido .linktienda {
    color: black<?php /*echo ($storeCode == 'n_es') ? 'black' : 'white';*/ ?>;
    width: 95%;
    text-align: center;
    margin-top: 30px;
    display: block;
    padding: 5px;
}
.pestana-contenido .linktienda span{
    width: 100%;
    display: block;
    text-align: center;
    font-size: 2.2rem;
    text-align: font-family;
    font-family: 'Open Sans';
    font-weight: 600;
}
.pestana-contenido .linktienda img{
   border-radius: 25px;
   padding:0px !important;

}
.pestana-contenido .contacto {
    bottom: 10px;
    position: absolute;
    width: 250px;
    padding: 10px;
}


.primera-barra {
    width: 100%;
    height: 100%;
    position: relative;
    background-color: <?php echo ($storeCode == 'n_es') ? '#cba472' : '#352e74'; ?>;

}
.cambiador.active .primera-barra {
    display: none;
}
.primera-barra .nobuck-icono {
    position: absolute;
    top: 30px;
    width: 30px;
    height: 30px;
    padding: 4px;
}
.primera-barra .tintopro-icono {
    position: absolute;
    top: 100px;
    width: 30px;
    height: 30px;
    padding: 4px;
}
.primera-barra .phone-icono {
    position: absolute;
    bottom: 50px;
    width: 30px;
    height: 30px;
    padding: 4px;
}
.primera-barra .mail-icono {
    position: absolute;
    bottom: 10px;
    width: 30px;
    height: 30px;
    padding: 4px;
}

.pestana-contenido .contacto div img{
    display: inline;
    width: 35px;
}
.pestana-contenido .contacto div span{
    color: white;
    margin-bottom: 5px;
    font-size: 20px;
}

</style>


<div class="cambiador">

    <div class="primera-barra">
        <img class="nobuck-icono" src="<?php echo $this->getViewFileUrl('images/nobuck-icono.png'); ?>" />
        <img class="tintopro-icono" src="<?php echo $this->getViewFileUrl('images/tintopro-icono.png'); ?>" />

        <img class="phone-icono" src="<?php echo $this->getViewFileUrl('images/phone.svg'); ?>" />
        <img class="mail-icono" src="<?php echo $this->getViewFileUrl('images/mail.svg'); ?>" />
    </div>

    <div class="pestana-contenido">

        <?php foreach ($block->getGroups() as $_group) : ?>
            <?php if (!($_group->getId() == $block->getCurrentGroupId())) : ?>
                <a class="linktienda" href="#" data-post='<?= $block->getTargetStorePostData($_group->getDefaultStore()) ?>'>
                    <img src="<?php echo ($_group->getId() == 2) ? $logoNobuck : $logoTintopro; ?>" />
                </a>
                <?php $store_puesto = $_group->getId(); ?>
            <?php endif; ?>
        <?php endforeach; ?>

        <a class="linktienda" href="#">
            <?php if ($store_puesto == 1): ?>
                <img src="<?= $logoNobuck ?>" />
            <?php else: ?>
                <img src="<?= $logoTintopro ?>" />
            <?php endif; ?>
        </a>

        <div class="contacto"> 
            <?php if ($storeCode == 'n_es'): ?>
                <div>
                    <img class="phone" src="<?php echo $this->getViewFileUrl('images/phone.svg'); ?>" />
                    <span>635434321</span>
                </div>
                <div>
                    <img class="mail" src="<?php echo $this->getViewFileUrl('images/mail.svg'); ?>" />
                    <span>info@tintopro.com</span>
                </div>
            <?php else: ?>
                <div>
                    <img class="phone" src="<?php echo $this->getViewFileUrl('images/phone.svg'); ?>" />
                    <span>635434321</span>
                </div>
                <div>
                    <img class="mail" src="<?php echo $this->getViewFileUrl('images/mail.svg'); ?>" />
                    <span>info@tintopro.com</span>
                </div>
            <?php endif; ?>
        </div>

    </div>

</div>





<script type="text/javascript">
    require(['jquery'],function($){
    	$(document).ready(function(){

            $('.cambiador').hover(function (e) {
                $('.cambiador').addClass('active');
                console.log('poniendo active');
            },function (e) {
                $('.cambiador').removeClass('active');
                console.log('desponiendo active');
            });

            $('.primera-barra').click(function (e) {
                $('.cambiador').hasClass('active') ?  $('.cambiador').removeClass('active') :  $('.cambiador').addClass('active');
                
            });

        });
    });


</script>